import { describe, expect, it } from "bun:test";
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "fs/promises";
import { createServer } from "net";
import { tmpdir } from "os";
import { join } from "path";
import {
  ensureInteractiveShellStartupReady,
  parseArgs,
  shouldActivateWizard,
} from "../../scripts/manual-test/index";
import {
  OPENCODE_DYNATRACE_PACKAGE_NAME,
  checkOpencodeAvailability,
  createFixtureWorkspace,
  createIsolatedOpenCodePaths,
  createIsolatedOpenCodePathsWithPluginSource,
  prepareWorkspacePluginSource,
  readIsolatedTestManifest,
  resolveHostOpenCodeConfigPath,
  resolveInstalledConfiguredPluginFromHostConfig,
} from "../e2e/helpers/harness";

const PROJECT_ROOT = join(import.meta.dir, "..", "..");
const DYNATRACE_PLUGIN_SPEC = `${OPENCODE_DYNATRACE_PACKAGE_NAME}@0.6.0`;

async function runLauncher(
  args: string[],
  extraEnv: Record<string, string> = {}
): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  const proc = Bun.spawn({
    // Use the current Bun executable explicitly; bare "bun" fails under restricted PATH.
    cmd: [process.execPath, "run", "scripts/manual-test/index.ts", "--", ...args],
    cwd: PROJECT_ROOT,
    env: {
      ...process.env,
      PATH: process.env.PATH ?? "",
      ...extraEnv,
    },
    stdout: "pipe",
    stderr: "pipe",
  });

  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);

  return { exitCode, stdout, stderr };
}

const opencodeCheck = await checkOpencodeAvailability();
const privateTestsEnabled = process.env.OPENCODE_CODER_PRIVATE_TESTS === "true";

describe("manual launcher preflight", () => {
  it("seeds isolated .zshrc for zsh shell mode in empty HOME", async () => {
    const tempHome = await mkdtemp(join(tmpdir(), "opencode-coder-zsh-home-"));

    try {
      const zshrcPath = join(tempHome, ".zshrc");
      await ensureInteractiveShellStartupReady("/bin/zsh", { HOME: tempHome });

      const seededFile = Bun.file(zshrcPath);
      expect(await seededFile.exists()).toBe(true);
      expect(await seededFile.text()).toContain("Generated by opencode-coder manual launcher");
    } finally {
      await rm(tempHome, { recursive: true, force: true });
    }
  });

  it("does not overwrite existing .zshrc during zsh shell setup", async () => {
    const tempHome = await mkdtemp(join(tmpdir(), "opencode-coder-zsh-home-existing-"));

    try {
      const zshrcPath = join(tempHome, ".zshrc");
      await writeFile(zshrcPath, "# existing zshrc\n", "utf8");

      await ensureInteractiveShellStartupReady("/bin/zsh", { HOME: tempHome });
      const finalContent = await readFile(zshrcPath, "utf8");
      expect(finalContent).toBe("# existing zshrc\n");
    } finally {
      await rm(tempHome, { recursive: true, force: true });
    }
  });

  it("does not create zsh startup files for non-zsh shells", async () => {
    const tempHome = await mkdtemp(join(tmpdir(), "opencode-coder-sh-home-"));

    try {
      const zshrcPath = join(tempHome, ".zshrc");
      await ensureInteractiveShellStartupReady("/bin/bash", { HOME: tempHome });

      const seededFile = Bun.file(zshrcPath);
      expect(await seededFile.exists()).toBe(false);
    } finally {
      await rm(tempHome, { recursive: true, force: true });
    }
  });

  it("activates wizard only when project source and mode are both implicit", () => {
    const implicit = parseArgs([]);
    expect(shouldActivateWizard(implicit)).toBe(true);

    const explicitFixture = parseArgs(["--fixture=cli-smoke-project"]);
    expect(shouldActivateWizard(explicitFixture)).toBe(false);

    const explicitProjectPath = parseArgs(["--project-path", "/tmp"]);
    expect(shouldActivateWizard(explicitProjectPath)).toBe(false);

    const explicitMode = parseArgs(["--mode=shell"]);
    expect(shouldActivateWizard(explicitMode)).toBe(false);
  });

  it("fails clearly in non-tty contexts without explicit source and mode", async () => {
    const result = await runLauncher([]);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain("Usage error: no project source or mode specified in non-interactive context");
    expect(result.stderr).toContain("Run with --help for usage.");
  });

  it("copies the committed OpenCode config fixture into isolated config", async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), "opencode-coder-isolated-config-"));

    try {
      const isolatedPaths = await createIsolatedOpenCodePaths(tempRoot);
      const opencodeConfig = await readFile(join(isolatedPaths.opencodeConfigDir, "opencode.json"), "utf8");

      expect(opencodeConfig).toContain(`"${DYNATRACE_PLUGIN_SPEC}"`);
      expect(opencodeConfig).not.toContain('"@dynatrace-oss/opencode-coder@0.34.2"');
      expect(opencodeConfig).toContain('"theme": "catppuccin"');
    } finally {
      await rm(tempRoot, { recursive: true, force: true });
    }
  });

  it("reads isolated test manifest pins used by harness setup", async () => {
    const manifest = await readIsolatedTestManifest();

    expect(manifest.pins["@hk9890/opencode-dynatrace"]).toBe("0.6.0");
    expect(manifest.pins["@opencode-ai/plugin"]).toBe("^1.2.16");
  });

  it("fails clearly for unknown fixture", async () => {
    const result = await runLauncher(["--mode=command", "--fixture=does-not-exist", "--", "env"]);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain("Unknown fixture: does-not-exist");
  });

  it("fails clearly for non-existent auth path", async () => {
    const result = await runLauncher([
      "--mode=command",
      "--fixture=cli-smoke-project",
      "--auth=/tmp/does-not-exist-auth.json",
      "--",
      "env",
    ]);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain("Auth seed error:");
    expect(result.stderr).not.toContain(" at ");
  });

  it("fails clearly when --project-path is missing a value", async () => {
    const result = await runLauncher(["--mode=command", "--project-path=", "--", "env"]);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain("Argument error: Missing value for --project-path");
  });

  it("fails clearly for invalid --project-path directory", async () => {
    const result = await runLauncher(["--mode=command", "--project-path=/tmp/does-not-exist-project", "--", "env"]);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain("Project path error: Project path does not exist:");
  });

  it("fails clearly when --fixture and --project-path are both set", async () => {
    const result = await runLauncher([
      "--mode=command",
      "--fixture=cli-smoke-project",
      "--project-path=/tmp",
      "--",
      "env",
    ]);

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain("Argument error: --fixture and --project-path are mutually exclusive");
  });

  it("resolves host config path precedence", () => {
    const fallbackPath = resolveHostOpenCodeConfigPath({}, "/tmp/fallback-home");
    expect(fallbackPath).toBe("/tmp/fallback-home/.config/opencode/opencode.json");

    const xdgPath = resolveHostOpenCodeConfigPath({ XDG_CONFIG_HOME: "/tmp/xdg-config" }, "/tmp/fallback-home");
    expect(xdgPath).toBe("/tmp/xdg-config/opencode/opencode.json");

    const explicitPath = resolveHostOpenCodeConfigPath(
      {
        OPENCODE_CONFIG_DIR: "/tmp/explicit-config",
        XDG_CONFIG_HOME: "/tmp/xdg-config",
      },
      "/tmp/fallback-home"
    );
    expect(explicitPath).toBe("/tmp/explicit-config/opencode.json");
  });

  it("resolves installed-configured package when exactly one matching plugin is configured", async () => {
    const hostConfigRoot = await mkdtemp(join(tmpdir(), "opencode-coder-host-config-ok-"));

    try {
      await writeFile(
        join(hostConfigRoot, "opencode.json"),
        JSON.stringify(
          {
            plugin: ["@hk9890/opencode-dynatrace@0.6.0", "@dynatrace-oss/opencode-coder@0.34.2"],
          },
          null,
          2
        ) + "\n",
        "utf8"
      );

      const resolved = await resolveInstalledConfiguredPluginFromHostConfig({ OPENCODE_CONFIG_DIR: hostConfigRoot });

      expect(resolved.packageSpec).toBe("@dynatrace-oss/opencode-coder@0.34.2");
      expect(resolved.hostConfigPath).toBe(join(hostConfigRoot, "opencode.json"));
    } finally {
      await rm(hostConfigRoot, { recursive: true, force: true });
    }
  });

  it("fails when host config has no matching installed opencode-coder entry", async () => {
    const hostConfigRoot = await mkdtemp(join(tmpdir(), "opencode-coder-host-config-none-"));

    try {
      await writeFile(
        join(hostConfigRoot, "opencode.json"),
        JSON.stringify(
          {
            plugin: ["@hk9890/opencode-dynatrace@0.6.0"],
          },
          null,
          2
        ) + "\n",
        "utf8"
      );

      await expect(
        resolveInstalledConfiguredPluginFromHostConfig({ OPENCODE_CONFIG_DIR: hostConfigRoot })
      ).rejects.toThrow("found 0");
    } finally {
      await rm(hostConfigRoot, { recursive: true, force: true });
    }
  });

  it("fails when host config has multiple matching opencode-coder entries", async () => {
    const hostConfigRoot = await mkdtemp(join(tmpdir(), "opencode-coder-host-config-many-"));

    try {
      await writeFile(
        join(hostConfigRoot, "opencode.json"),
        JSON.stringify(
          {
            plugin: [
              "@dynatrace-oss/opencode-coder@0.34.1",
              "@dynatrace-oss/opencode-coder@0.34.2",
              "@hk9890/opencode-dynatrace@0.6.0",
            ],
          },
          null,
          2
        ) + "\n",
        "utf8"
      );

      await expect(
        resolveInstalledConfiguredPluginFromHostConfig({ OPENCODE_CONFIG_DIR: hostConfigRoot })
      ).rejects.toThrow("found 2");
    } finally {
      await rm(hostConfigRoot, { recursive: true, force: true });
    }
  });

  it("seeds installed-configured isolated config without configured opencode-coder entry", async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), "opencode-coder-installed-config-seed-"));

    try {
      const isolatedPaths = await createIsolatedOpenCodePathsWithPluginSource(tempRoot, {
        pluginSource: "installed-configured",
      });

      const opencodeConfig = await readFile(join(isolatedPaths.opencodeConfigDir, "opencode.json"), "utf8");
      expect(opencodeConfig).toContain(`"${DYNATRACE_PLUGIN_SPEC}"`);
      expect(opencodeConfig).not.toContain('"@dynatrace-oss/opencode-coder@0.34.2"');
      expect(Object.prototype.hasOwnProperty.call(isolatedPaths.env, "OPENCODE_DISABLE_DEFAULT_PLUGINS")).toBe(true);
    } finally {
      await rm(tempRoot, { recursive: true, force: true });
    }
  });

  it.skipIf(!privateTestsEnabled)("prepares pinned Dynatrace package deterministically for isolated local-build startup", async () => {
    const workspace = await createFixtureWorkspace("cli-smoke-project");

    try {
      await prepareWorkspacePluginSource({
        projectRoot: PROJECT_ROOT,
        workdir: workspace.workdir,
        pluginSource: "local-build",
      });

      const dynatracePackageJsonPath = join(
        workspace.workdir,
        ".opencode",
        "node_modules",
        "@hk9890",
        "opencode-dynatrace",
        "package.json"
      );
      const packageJson = JSON.parse(await readFile(dynatracePackageJsonPath, "utf8")) as { version?: string };
      expect(packageJson.version).toBe("0.6.0");
    } finally {
      await rm(workspace.tempRoot, { recursive: true, force: true });
    }
  }, 120000);
});

describe.skipIf(!opencodeCheck.available || !privateTestsEnabled)("manual launcher non-interactive mode", () => {
  it("runs one-shot command with shared isolated setup and explicit auth seed", async () => {
    const tempAuthDir = await mkdtemp(join(tmpdir(), "opencode-coder-manual-auth-"));
    const authPath = join(tempAuthDir, "auth.json");
    await writeFile(authPath, "{}\n", "utf8");

    let preservedRoot: string | undefined;

    try {
      const result = await runLauncher([
        "--mode=command",
        "--fixture=cli-smoke-project",
        `--auth=${authPath}`,
        "--",
        "env",
      ], {
        OPENCODE_DEFAULT_OPTIONS: "--log-level DEBUG",
        OPENCODE_LOG_RETENTION: "100",
        MANUAL_LAUNCHER_ENV_LEAK_CANARY: "should-not-leak",
      });

      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain("Mode: command");
      expect(result.stdout).toContain("Plugin source: local-build");
      expect(result.stdout).toContain("Execution model: fixture copy (disposable workspace)");
      expect(result.stdout).toContain("Fixture: cli-smoke-project");
      expect(result.stdout).toContain("Project source:");
      expect(result.stdout).toContain("Workdir:");
      expect(result.stdout).toContain("Auth seeded: yes (explicit-path)");
      expect(result.stdout).toContain("Plugin path used:");
      expect(result.stdout).toContain("Resolved installed package: <none>");
      expect(result.stdout).toContain("Resolved host config: <none>");
      expect(result.stdout).toContain("Configured plugin loading: disabled (OPENCODE_DISABLE_DEFAULT_PLUGINS=true)");
      expect(result.stdout).toContain("Loaded plugin version:");
      expect(result.stdout).toContain("Cleanup plan: preserve copied workspace and isolated environment");
      expect(result.stdout).not.toContain("--keep: accepted (backward-compatible no-op)");
      expect(result.stdout).toContain("OPENCODE_DISABLE_DEFAULT_PLUGINS=true");
      expect(result.stdout).toContain("OPENCODE_CONFIG_DIR=");
      expect(result.stdout).not.toContain("OPENCODE_DEFAULT_OPTIONS=");
      expect(result.stdout).not.toContain("OPENCODE_LOG_RETENTION=");
      expect(result.stdout).not.toContain("MANUAL_LAUNCHER_ENV_LEAK_CANARY=");

      const envLineCount = result.stdout
        .split("\n")
        .map((line) => line.trim())
        .filter((line) => /^[A-Za-z_][A-Za-z0-9_]*=/.test(line)).length;
      expect(envLineCount).toBeGreaterThanOrEqual(8);
      expect(envLineCount).toBeLessThan(30);

      const preservedMatch = result.stdout.match(/Environment preserved at: (.+)\n?/);
      expect(preservedMatch).not.toBeNull();
      preservedRoot = preservedMatch?.[1]?.trim();
      expect(Boolean(preservedRoot)).toBe(true);
      expect(preservedRoot).toContain(`${join(".manual-test-runs", "run-")}`);

      const pluginLink = Bun.file(join(preservedRoot!, "project", ".opencode", "plugins", "opencode-coder.js"));
      const dynatracePackageJsonPath = join(
        preservedRoot!,
        "project",
        ".opencode",
        "node_modules",
        "@hk9890",
        "opencode-dynatrace",
        "package.json"
      );
      const isolatedAuth = Bun.file(join(preservedRoot!, "isolated-opencode", "xdg-data", "opencode", "auth.json"));
      const isolatedConfig = await readFile(
        join(preservedRoot!, "isolated-opencode", "xdg-config", "opencode", "opencode.json"),
        "utf8"
      );

      expect(await pluginLink.exists()).toBe(true);
      expect(await isolatedAuth.exists()).toBe(true);
      expect(isolatedConfig).toContain(`"${DYNATRACE_PLUGIN_SPEC}"`);
      expect(isolatedConfig).not.toContain('"@dynatrace-oss/opencode-coder@0.34.2"');

      const dynatracePackageJson = JSON.parse(await readFile(dynatracePackageJsonPath, "utf8")) as {
        version?: string;
      };
      expect(dynatracePackageJson.version).toBe("0.6.0");
    } finally {
      if (preservedRoot) {
        await rm(preservedRoot, { recursive: true, force: true });
      }
      await rm(tempAuthDir, { recursive: true, force: true });
    }
  }, 120000);

  it("runs one-shot command with external --project-path directly in place", async () => {
    const sourceRoot = await mkdtemp(join(tmpdir(), "opencode-coder-manual-project-source-"));
    const sourceAuthDir = await mkdtemp(join(tmpdir(), "opencode-coder-manual-auth-"));
    const authPath = join(sourceAuthDir, "auth.json");
    await writeFile(authPath, "{}\n", "utf8");

    await mkdir(join(sourceRoot, ".git"), { recursive: true });
    await mkdir(join(sourceRoot, ".beads"), { recursive: true });
    await mkdir(join(sourceRoot, ".coder"), { recursive: true });
    await mkdir(join(sourceRoot, ".opencode", "commands"), { recursive: true });
    await writeFile(join(sourceRoot, ".git", "SENTINEL"), "copied-git-metadata\n", "utf8");
    await writeFile(join(sourceRoot, ".beads", "daemon.pid"), "123\n", "utf8");
    await writeFile(join(sourceRoot, ".coder", "project.yaml"), "pluginVersion: stale\n", "utf8");
    await writeFile(join(sourceRoot, ".coder", "opencode-coder.yaml"), "mode: team\n", "utf8");
    await writeFile(join(sourceRoot, ".opencode", "commands", "local-command.md"), "# local command\n", "utf8");
    await symlink("/tmp/opencode-coder-missing-command.md", join(sourceRoot, ".opencode", "commands", "broken-link.md"));
    await writeFile(join(sourceRoot, "README.md"), "external project fixture\n", "utf8");

    const sourceSocketPath = join(sourceRoot, ".beads", "bd.sock");
    const sourceSocketServer = createServer();
    await new Promise<void>((resolve, reject) => {
      sourceSocketServer.once("error", reject);
      sourceSocketServer.listen(sourceSocketPath, () => {
        sourceSocketServer.off("error", reject);
        resolve();
      });
    });

    let preservedRoot: string | undefined;

    try {
      const result = await runLauncher([
        "--mode=command",
        "--project-path",
        sourceRoot,
        "--keep",
        `--auth=${authPath}`,
        "--",
        "env",
      ]);

      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain("Mode: command");
      expect(result.stdout).toContain("Plugin source: local-build");
      expect(result.stdout).toContain("Execution model: direct project path (in place)");
      expect(result.stdout).toContain(`Project path: ${sourceRoot}`);
      expect(result.stdout).toContain(`Project source: ${sourceRoot}`);
      expect(result.stdout).toContain(`Workdir: ${sourceRoot}`);
      expect(result.stdout).toContain("Auth seeded: yes (explicit-path)");
      expect(result.stdout).toContain("Project mutation risk: yes (project-path runs execute in place)");

      const preservedMatch = result.stdout.match(/Environment preserved at: (.+)\n?/);
      expect(preservedMatch).not.toBeNull();
      preservedRoot = preservedMatch?.[1]?.trim();
      expect(Boolean(preservedRoot)).toBe(true);
      expect(preservedRoot).toContain(`${join(".manual-test-runs", "run-")}`);

      const preservedProjectDir = Bun.file(join(preservedRoot!, "project"));
      const isolatedConfig = Bun.file(join(preservedRoot!, "isolated-opencode", "xdg-config", "opencode", "opencode.json"));
      const isolatedAuth = Bun.file(join(preservedRoot!, "isolated-opencode", "xdg-data", "opencode", "auth.json"));
      const sourceReadme = Bun.file(join(sourceRoot, "README.md"));
      const sourceGitSentinel = Bun.file(join(sourceRoot, ".git", "SENTINEL"));
      const sourceBeadsPid = Bun.file(join(sourceRoot, ".beads", "daemon.pid"));
      const sourceBeadsSocket = Bun.file(join(sourceRoot, ".beads", "bd.sock"));
      const sourceCoderProject = Bun.file(join(sourceRoot, ".coder", "project.yaml"));
      const sourceCoderModeState = Bun.file(join(sourceRoot, ".coder", "opencode-coder.yaml"));
      const sourceOpencodeLocalCommand = Bun.file(join(sourceRoot, ".opencode", "commands", "local-command.md"));
      const sourceOpencodeBrokenLink = Bun.file(join(sourceRoot, ".opencode", "commands", "broken-link.md"));
      const sourcePluginLink = Bun.file(join(sourceRoot, ".opencode", "plugins", "opencode-coder.js"));

      expect(await preservedProjectDir.exists()).toBe(false);
      expect(await isolatedConfig.exists()).toBe(true);
      expect(await isolatedAuth.exists()).toBe(true);
      expect(await sourceReadme.exists()).toBe(true);
      expect(await sourceGitSentinel.exists()).toBe(true);
      expect(await sourceBeadsPid.exists()).toBe(true);
      expect(await sourceBeadsSocket.exists()).toBe(true);
      expect(await sourceCoderProject.exists()).toBe(true);
      expect(await sourceCoderProject.text()).toContain("pluginVersion: stale");
      expect(await sourceCoderModeState.exists()).toBe(true);
      expect(await sourceCoderModeState.text()).toContain("mode: team");
      expect(await sourceOpencodeLocalCommand.exists()).toBe(true);
      expect(await sourceOpencodeBrokenLink.exists()).toBe(false);
      expect(await sourcePluginLink.exists()).toBe(true);
    } finally {
      await new Promise<void>((resolve, reject) => {
        sourceSocketServer.close((error) => {
          if (error) {
            reject(error);
            return;
          }

          resolve();
        });
      });
      if (preservedRoot) {
        await rm(preservedRoot, { recursive: true, force: true });
      }
      await rm(sourceRoot, { recursive: true, force: true });
      await rm(sourceAuthDir, { recursive: true, force: true });
    }
  }, 120000);

  it("supports installed-configured plugin source with deterministic package prep and version proof", async () => {
    const hostConfigRoot = await mkdtemp(join(tmpdir(), "opencode-coder-launcher-installed-source-"));

    await writeFile(
      join(hostConfigRoot, "opencode.json"),
      JSON.stringify(
        {
          plugin: ["@dynatrace-oss/opencode-coder@0.34.2", "@hk9890/opencode-dynatrace@0.6.0"],
        },
        null,
        2
      ) + "\n",
      "utf8"
    );

    let preservedRoot: string | undefined;

    try {
      const result = await runLauncher(
        [
          "--mode=command",
          "--fixture=existing-active-project",
          "--plugin-source=installed-configured",
          "--keep",
          "--",
          "node",
          join(PROJECT_ROOT, "tests", "e2e", "helpers", "manual-launcher-plugin-proof.mjs"),
        ],
        {
          OPENCODE_CONFIG_DIR: hostConfigRoot,
        }
      );

      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain("Plugin source: installed-configured");
      expect(result.stdout).toContain("Plugin path used:");
      expect(result.stdout).not.toContain("Plugin path used: <none>");
      expect(result.stdout).toContain("Resolved installed package: @dynatrace-oss/opencode-coder@0.34.2");
      expect(result.stdout).toContain(`Resolved host config: ${join(hostConfigRoot, "opencode.json")}`);
      expect(result.stdout).toContain("Configured plugin loading: disabled (OPENCODE_DISABLE_DEFAULT_PLUGINS=true)");
      expect(result.stdout).toContain("Expected installed plugin version: 0.34.2");
      expect(result.stdout).toContain("Loaded plugin version:");
      expect(result.stdout).toContain("Installed plugin load proof: valid");
      expect(result.stdout).toContain("PLUGIN_PROOF_OK:0.34.2");
      expect(result.stdout).not.toContain("INVALID_COMPARISON");

      const preservedMatch = result.stdout.match(/Environment preserved at: (.+)\n?/);
      expect(preservedMatch).not.toBeNull();
      preservedRoot = preservedMatch?.[1]?.trim();
      expect(Boolean(preservedRoot)).toBe(true);
      expect(preservedRoot).toContain(`${join(".manual-test-runs", "run-")}`);

      const pluginLink = Bun.file(join(preservedRoot!, "project", ".opencode", "plugins", "opencode-coder.js"));
      expect(await pluginLink.exists()).toBe(true);

      const isolatedConfig = await readFile(
        join(preservedRoot!, "isolated-opencode", "xdg-config", "opencode", "opencode.json"),
        "utf8"
      );
      expect(isolatedConfig).toContain(`"${DYNATRACE_PLUGIN_SPEC}"`);
      expect(isolatedConfig).not.toContain('"@dynatrace-oss/opencode-coder@0.34.2"');
    } finally {
      if (preservedRoot) {
        await rm(preservedRoot, { recursive: true, force: true });
      }
      await rm(hostConfigRoot, { recursive: true, force: true });
    }
  }, 120000);

  it("fails installed-configured run when plugin load proof remains fixture baseline", async () => {
    const hostConfigRoot = await mkdtemp(join(tmpdir(), "opencode-coder-launcher-installed-source-negative-"));

    await writeFile(
      join(hostConfigRoot, "opencode.json"),
      JSON.stringify(
        {
          plugin: ["@dynatrace-oss/opencode-coder@0.34.2", "@hk9890/opencode-dynatrace@0.6.0"],
        },
        null,
        2
      ) + "\n",
      "utf8"
    );

    let preservedRoot: string | undefined;

    try {
      const result = await runLauncher(
        [
          "--mode=command",
          "--fixture=existing-active-project",
          "--plugin-source=installed-configured",
          "--keep",
          "--",
          "env",
        ],
        {
          OPENCODE_CONFIG_DIR: hostConfigRoot,
        }
      );

      expect(result.exitCode).toBe(1);
      expect(result.stdout).toContain("Plugin source: installed-configured");
      expect(result.stdout).toContain("Expected installed plugin version: 0.34.2");
      expect(result.stdout).toContain("Loaded plugin version: fixture");
      expect(result.stdout).toContain("Installed plugin load proof: MISSING_OR_INVALID");
      expect(result.stderr).toContain("INVALID_COMPARISON: installed-configured plugin load proof missing");

      const preservedMatch = result.stdout.match(/Environment preserved at: (.+)\n?/);
      expect(preservedMatch).not.toBeNull();
      preservedRoot = preservedMatch?.[1]?.trim();
      expect(Boolean(preservedRoot)).toBe(true);
      expect(preservedRoot).toContain(`${join(".manual-test-runs", "run-")}`);
    } finally {
      if (preservedRoot) {
        await rm(preservedRoot, { recursive: true, force: true });
      }
      await rm(hostConfigRoot, { recursive: true, force: true });
    }
  }, 120000);
});
