#!/usr/bin/env bun

import { spawn } from "child_process";
import { input, select } from "@inquirer/prompts";
import { mkdir, mkdtemp, stat, writeFile } from "fs/promises";
import { basename, join } from "path";
import {
  FIXTURE_NAMES,
  type FixtureName,
  checkOpencodeAvailability,
  createFixtureWorkspace,
  createIsolatedOpenCodePaths,
  createProjectPathWorkspace,
  isFixtureName,
  type PluginSource,
  prepareCoderFixtureResources,
  prepareWorkspacePluginSource,
  resolveAuthSeedPath,
  seedIsolatedOpenCodeAuth,
} from "../../tests/e2e/helpers/harness";

type LauncherMode = "tui" | "shell" | "command";

const BASE_ENV_KEYS = ["USER", "LOGNAME", "LANG"] as const;
const INTERACTIVE_ENV_KEYS = [
  "TERM",
  "COLORTERM",
  "TERMINFO",
  "DISPLAY",
  "WAYLAND_DISPLAY",
  "XDG_RUNTIME_DIR",
  "XDG_SESSION_CLASS",
  "XDG_SESSION_DESKTOP",
  "XDG_SESSION_TYPE",
  "XDG_CURRENT_DESKTOP",
  "DBUS_SESSION_BUS_ADDRESS",
] as const;

function copyDefinedEnvKey(
  sourceEnv: NodeJS.ProcessEnv,
  targetEnv: Record<string, string | undefined>,
  key: string
): void {
  const value = sourceEnv[key];
  if (value !== undefined && value !== "") {
    targetEnv[key] = value;
  }
}

function buildChildEnv(
  mode: LauncherMode,
  isolatedEnv: Record<string, string | undefined>,
  extraPathDirs: string[] = [],
  sourceEnv: NodeJS.ProcessEnv = process.env
): Record<string, string | undefined> {
  // Child env is intentionally allowlist-only to preserve e2e isolation parity.
  // Do not spread process.env here.
  const childEnv: Record<string, string | undefined> = {
    PATH: [...extraPathDirs, sourceEnv.PATH ?? ""].filter((entry) => entry && entry.length > 0).join(":"),
  };

  for (const key of BASE_ENV_KEYS) {
    copyDefinedEnvKey(sourceEnv, childEnv, key);
  }

  for (const [key, value] of Object.entries(sourceEnv)) {
    if (key.startsWith("LC_") && value !== undefined && value !== "") {
      childEnv[key] = value;
    }
  }

  if (mode === "tui" || mode === "shell") {
    for (const key of INTERACTIVE_ENV_KEYS) {
      copyDefinedEnvKey(sourceEnv, childEnv, key);
    }
  }

  if (mode === "shell") {
    copyDefinedEnvKey(sourceEnv, childEnv, "SHELL");
  }

  return {
    ...childEnv,
    ...isolatedEnv,
  };
}

export async function ensureInteractiveShellStartupReady(
  shellPath: string,
  env: Record<string, string | undefined>
): Promise<void> {
  const shellName = basename(shellPath).toLowerCase();
  if (shellName !== "zsh") {
    return;
  }

  const homeDir = env.HOME?.trim();
  if (!homeDir) {
    return;
  }

  const zdotdir = env.ZDOTDIR?.trim() || homeDir;
  const zshrcPath = join(zdotdir, ".zshrc");
  const existing = await stat(zshrcPath).catch(() => null);
  if (existing) {
    return;
  }

  await mkdir(zdotdir, { recursive: true });
  await writeFile(
    zshrcPath,
    "# Generated by opencode-coder manual launcher for isolated shell sessions.\n",
    "utf8"
  );
}

interface ParsedArgs {
  mode: LauncherMode;
  pluginSource: PluginSource;
  fixture?: string;
  projectPath?: string;
  keep: boolean;
  authPath?: string;
  requireAuth: boolean;
  command: string[];
  help: boolean;
  explicitProjectSource: boolean;
  explicitMode: boolean;
}

const PROJECT_ROOT = join(import.meta.dir, "..", "..");
const DEFAULT_FIXTURE: FixtureName = "empty-project";
const MANUAL_RUNS_ROOT = join(PROJECT_ROOT, ".manual-test-runs");

interface WizardSelection {
  fixture?: FixtureName;
  projectPath?: string;
  mode: Exclude<LauncherMode, "command">;
}

const FIXTURE_DESCRIPTIONS: Record<FixtureName, { label: string; help: string }> = {
  "empty-project": {
    label: "empty-project — runtime workspace is intentionally empty",
    help: "empty-project — runtime baseline: no README/.gitkeep scaffolding, no .coder state, and no seeded project-local .opencode resources",
  },
  "coder-mode-configured": {
    label: "coder-mode-configured — only first-stage .coder mode state",
    help: "coder-mode-configured — runtime baseline: .coder/opencode-coder.yaml only; no README/.gitkeep scaffolding and no seeded project-local .opencode resources",
  },
  "coder-skill-installed": {
    label: "coder-skill-installed — stage-2 coder runtime (non-beads)",
    help: "coder-skill-installed — runtime stage 2: aimgr installs coder-core/coder-support/coder-docs only; no coder-beads, no orchestrator agent, no .beads",
  },
  "beads-initialized": {
    label: "beads-initialized — stage-3 beads/orchestrator ready",
    help: "beads-initialized — runtime stage 3: stage-2 coder packages + coder-beads, agents/orchestrator available, and initialized .beads state",
  },
};

function formatFixtureHelpLines(): string {
  return FIXTURE_NAMES.map((fixtureName) => `  ${FIXTURE_DESCRIPTIONS[fixtureName].help}`).join("\n");
}

function printHelp(): void {
  console.log(`Manual isolated plugin test launcher

Usage:
  bun run test:manual -- [options]
  bun run test:manual -- --mode=command --fixture=empty-project -- env

No-arg behavior:
  Interactive wizard (TTY only) asks for project source and mode (tui/shell).
  In non-TTY contexts, pass --fixture/--project-path and --mode explicitly.

Modes:
  --mode=tui        Launch interactive OpenCode TUI (default)
  --mode=shell      Launch interactive shell in isolated project
  --mode=command    Run one-shot command (arguments after --)
  --tui             Alias for --mode=tui
  --shell           Alias for --mode=shell
  --command         Alias for --mode=command

Options:
  --fixture=<name>  Fixture to copy
  --project-path    External project directory to run against in place (no copy)
  --plugin-source=<mode> Plugin source: local-build (default) | installed-configured
  --auth=<path>     Explicit auth.json path seed (copied to isolated XDG data)
  --require-auth    Fail if no auth seed source is available
  --keep            Backward-compatible no-op (workspace is always preserved)
  -h, --help        Show this help

Available fixtures:
${formatFixtureHelpLines()}

Notes:
  Run bun run test:launcher:preflight before release work for env-stripped launcher/setup validation.
  --fixture selects a committed fixture baseline, then prepares a runtime workspace for the chosen mode/plugin source.
  --project-path runs against the provided project without copying it.
  Launcher-owned plugin/resources are prepared in isolated OPENCODE_CONFIG_DIR state, not written into the target project.
  Shell and TUI runs prepare the same runtime workspace state; shell stops before launching OpenCode.
  installed-configured requires explicit GitHub Packages auth (NODE_AUTH_TOKEN) and configured host plugin entry.
  Existing project-local OpenCode config/resources may still be read according to normal OpenCode precedence.
  Resource/bootstrap depth depends on fixture stage (for example empty-project and coder-mode-configured stay minimally prepared).
  Beads fixtures may also receive best-effort runtime .beads init.
  Runtime-generated .coder/project.yaml is authoritative whenever startup rewrites project state.
  Isolated OpenCode runtime data is prewarmed from an empty baseline when available to avoid repeated first-run DB migration cost.
  Automated launcher guardrails cover environment preparation + startup viability only.
  Auth/model-backed prompts (for example: "say hi") are exploratory manual checks.
  "env" remains useful for launcher-environment debugging only.
`);
}

export function parseArgs(argv: string[]): ParsedArgs {
  const parsed: ParsedArgs = {
    mode: "tui",
    pluginSource: "local-build",
    keep: false,
    requireAuth: false,
    command: [],
    help: false,
    explicitProjectSource: false,
    explicitMode: false,
  };

  let i = 0;
  while (i < argv.length) {
    const arg = argv[i];

    if (arg === "--") {
      parsed.command = argv.slice(i + 1);
      break;
    }

    if (arg === "-h" || arg === "--help") {
      parsed.help = true;
      i++;
      continue;
    }

    if (arg === "--keep") {
      parsed.keep = true;
      i++;
      continue;
    }

    if (arg === "--require-auth") {
      parsed.requireAuth = true;
      i++;
      continue;
    }

    if (arg === "--tui") {
      parsed.mode = "tui";
      parsed.explicitMode = true;
      i++;
      continue;
    }

    if (arg === "--shell") {
      parsed.mode = "shell";
      parsed.explicitMode = true;
      i++;
      continue;
    }

    if (arg === "--command") {
      parsed.mode = "command";
      parsed.explicitMode = true;
      i++;
      continue;
    }

    if (arg.startsWith("--mode=")) {
      const mode = arg.slice("--mode=".length);
      if (mode === "tui" || mode === "shell" || mode === "command") {
        parsed.mode = mode;
        parsed.explicitMode = true;
      } else {
        throw new Error(`Unknown mode: ${mode}`);
      }
      i++;
      continue;
    }

    if (arg === "--mode") {
      const mode = argv[i + 1];
      if (!mode || !["tui", "shell", "command"].includes(mode)) {
        throw new Error("Expected one of: tui, shell, command");
      }
      parsed.mode = mode as LauncherMode;
      parsed.explicitMode = true;
      i += 2;
      continue;
    }

    if (arg.startsWith("--fixture=")) {
      parsed.fixture = arg.slice("--fixture=".length);
      parsed.explicitProjectSource = true;
      i++;
      continue;
    }

    if (arg === "--fixture") {
      const fixture = argv[i + 1];
      if (!fixture) {
        throw new Error("Missing value for --fixture");
      }
      parsed.fixture = fixture;
      parsed.explicitProjectSource = true;
      i += 2;
      continue;
    }

    if (arg.startsWith("--project-path=")) {
      const projectPath = arg.slice("--project-path=".length);
      if (!projectPath.trim()) {
        throw new Error("Missing value for --project-path");
      }
      parsed.projectPath = projectPath;
      parsed.explicitProjectSource = true;
      i++;
      continue;
    }

    if (arg === "--project-path") {
      const projectPath = argv[i + 1];
      if (!projectPath || projectPath === "--") {
        throw new Error("Missing value for --project-path");
      }
      parsed.projectPath = projectPath;
      parsed.explicitProjectSource = true;
      i += 2;
      continue;
    }

    if (arg.startsWith("--plugin-source=")) {
      const pluginSource = arg.slice("--plugin-source=".length);
      if (pluginSource === "local-build" || pluginSource === "installed-configured") {
        parsed.pluginSource = pluginSource;
      } else {
        throw new Error(`Unknown plugin source: ${pluginSource}`);
      }
      i++;
      continue;
    }

    if (arg === "--plugin-source") {
      const pluginSource = argv[i + 1];
      if (!pluginSource || !["local-build", "installed-configured"].includes(pluginSource)) {
        throw new Error("Expected one of: local-build, installed-configured");
      }
      parsed.pluginSource = pluginSource as PluginSource;
      i += 2;
      continue;
    }

    if (arg.startsWith("--auth=")) {
      parsed.authPath = arg.slice("--auth=".length);
      i++;
      continue;
    }

    if (arg === "--auth") {
      const authPath = argv[i + 1];
      if (!authPath) {
        throw new Error("Missing value for --auth");
      }
      parsed.authPath = authPath;
      i += 2;
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  if (parsed.mode === "command" && parsed.command.length === 0) {
    throw new Error("Command mode requires command arguments after '--'");
  }

  if (parsed.fixture !== undefined && parsed.projectPath !== undefined) {
    throw new Error("--fixture and --project-path are mutually exclusive");
  }

  return parsed;
}

export function shouldActivateWizard(args: ParsedArgs): boolean {
  return !args.explicitProjectSource && !args.explicitMode;
}

async function runWizard(): Promise<WizardSelection> {
  const source = await select<{ kind: "fixture" } | { kind: "project-path" }>({
    message: "Project source",
    choices: [
      {
        name: "Use fixture",
        value: { kind: "fixture" },
      },
      {
        name: "Use external project path",
        value: { kind: "project-path" },
      },
    ],
  });

  let fixture: FixtureName | undefined;
  let projectPath: string | undefined;

  if (source.kind === "fixture") {
    fixture = await select<FixtureName>({
      message: "Fixture",
      choices: FIXTURE_NAMES.map((fixtureName) => ({
        name: FIXTURE_DESCRIPTIONS[fixtureName].label,
        value: fixtureName,
      })),
      default: DEFAULT_FIXTURE,
    });
  } else {
    const rawPath = await input({
      message: "Project path",
      validate: (value) => (value.trim().length > 0 ? true : "Project path is required"),
    });
    projectPath = rawPath.trim();
  }

  const mode = await select<"tui" | "shell">({
    message: "Mode",
    choices: [
      {
        name: "TUI",
        value: "tui",
      },
      {
        name: "Shell",
        value: "shell",
      },
    ],
  });

  return {
    fixture,
    projectPath,
    mode,
  };
}

async function validateProjectPath(projectPath: string): Promise<string> {
  const normalizedPath = projectPath.trim();
  if (!normalizedPath) {
    throw new Error("Missing value for --project-path");
  }

  const metadata = await stat(normalizedPath).catch(() => null);
  if (!metadata) {
    throw new Error(`Project path does not exist: ${normalizedPath}`);
  }

  if (!metadata.isDirectory()) {
    throw new Error(`Project path is not a directory: ${normalizedPath}`);
  }

  return normalizedPath;
}

function printSection(title: string, value: string): void {
  console.log(`${title}: ${value}`);
}

function exitReason(exitCode: number, signalCode: NodeJS.Signals | null): string {
  if (signalCode) {
    return `signal ${signalCode}`;
  }
  return `exit code ${exitCode}`;
}

function signalToExitCode(signalCode: NodeJS.Signals | null): number {
  switch (signalCode) {
    case "SIGINT":
      return 130;
    case "SIGTERM":
      return 143;
    default:
      return 1;
  }
}

function sanitizeSpawnEnv(env: Record<string, string | undefined>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(env).filter((entry): entry is [string, string] => typeof entry[1] === "string")
  );
}

function requiresOpenCodeBootstrap(mode: LauncherMode): boolean {
  return true;
}

function requiresOpencodeBinary(mode: LauncherMode): boolean {
  return mode === "tui";
}

export function buildInteractiveShellCommand(shellPath: string): string[] {
  const normalizedShell = shellPath.trim() || "/bin/sh";
  const shellName = basename(normalizedShell).toLowerCase();

  switch (shellName) {
    case "sh":
    case "bash":
    case "zsh":
    case "fish":
      return [normalizedShell, "-i"];
    default:
      return [normalizedShell];
  }
}

async function runInteractive(
  cmd: string[],
  cwd: string,
  env: Record<string, string | undefined>
): Promise<{ exitCode: number; signalCode: NodeJS.Signals | null }> {
  return await new Promise((resolve, reject) => {
    const [command, ...args] = cmd;
    const child = spawn(command, args, {
      cwd,
      env: sanitizeSpawnEnv(env),
      stdio: "inherit",
    });

    let settled = false;

    const cleanup = () => {
      process.off("SIGINT", forwardSignal);
      process.off("SIGTERM", forwardSignal);
      child.off("error", onError);
      child.off("exit", onExit);
    };

    const settle = (fn: () => void) => {
      if (settled) {
        return;
      }
      settled = true;
      cleanup();
      fn();
    };

    const forwardSignal = (signal: NodeJS.Signals) => {
      if (child.exitCode !== null || child.signalCode !== null) {
        return;
      }
      try {
        child.kill(signal);
      } catch {
        // Child may already be exiting.
      }
    };

    const onError = (error: Error) => {
      settle(() => reject(error));
    };

    const onExit = (exitCode: number | null, signalCode: NodeJS.Signals | null) => {
      settle(() =>
        resolve({
          exitCode: exitCode ?? signalToExitCode(signalCode),
          signalCode,
        })
      );
    };

    process.on("SIGINT", forwardSignal);
    process.on("SIGTERM", forwardSignal);
    child.on("error", onError);
    child.on("exit", onExit);
  });
}

async function runCaptured(
  cmd: string[],
  cwd: string,
  env: Record<string, string | undefined>
): Promise<{ exitCode: number; signalCode: NodeJS.Signals | null; stdout: string; stderr: string }> {
  const child = Bun.spawn({
    cmd,
    cwd,
    env,
    stdout: "pipe",
    stderr: "pipe",
  });

  const forwardSignal = (signal: NodeJS.Signals) => {
    try {
      child.kill(signal);
    } catch {
      // Child may already be exiting.
    }
  };

  process.on("SIGINT", forwardSignal);
  process.on("SIGTERM", forwardSignal);

  try {
    const [stdout, stderr, exitCode] = await Promise.all([
      new Response(child.stdout).text(),
      new Response(child.stderr).text(),
      child.exited,
    ]);

    return {
      exitCode,
      signalCode: child.signalCode,
      stdout,
      stderr,
    };
  } finally {
    process.off("SIGINT", forwardSignal);
    process.off("SIGTERM", forwardSignal);
  }
}

export async function main(argv = process.argv.slice(2)): Promise<number> {
  let args: ParsedArgs;
  try {
    args = parseArgs(argv);
  } catch (error) {
    console.error(`Argument error: ${(error as Error).message}`);
    console.error("Run with --help for usage.");
    return 2;
  }

  if (args.help) {
    printHelp();
    return 0;
  }

  const shouldRunWizard = shouldActivateWizard(args);
  if (shouldRunWizard) {
    if (!process.stdin.isTTY) {
      console.error(
        "Usage error: no project source or mode specified in non-interactive context. Pass --fixture/--project-path and --mode explicitly."
      );
      console.error("Run with --help for usage.");
      return 2;
    }

    try {
      const wizardSelection = await runWizard();
      args.mode = wizardSelection.mode;
      args.fixture = wizardSelection.fixture;
      args.projectPath = wizardSelection.projectPath;
    } catch (error) {
      console.error(`Wizard canceled: ${(error as Error).message}`);
      return 130;
    }
  }

  if (args.fixture === undefined && args.projectPath === undefined) {
    args.fixture = DEFAULT_FIXTURE;
  }

  if (args.fixture && !isFixtureName(args.fixture)) {
    console.error(`Unknown fixture: ${args.fixture}`);
    console.error(`Available fixtures: ${FIXTURE_NAMES.join(", ")}`);
    return 2;
  }

  let validatedProjectPath: string | undefined;
  if (args.projectPath !== undefined) {
    try {
      validatedProjectPath = await validateProjectPath(args.projectPath);
    } catch (error) {
      console.error(`Project path error: ${(error as Error).message}`);
      return 2;
    }
  }

  let authSeedPath: ReturnType<typeof resolveAuthSeedPath>;
  try {
    authSeedPath = resolveAuthSeedPath(args.authPath);
  } catch (error) {
    console.error(`Auth seed error: ${(error as Error).message}`);
    return 2;
  }

  if (args.requireAuth && !authSeedPath) {
    console.error("No usable auth seed found.");
    console.error("Provide --auth <path> or ensure ~/.local/share/opencode/auth.json exists.");
    return 1;
  }

  let extraPathDirs: string[] = [];
  if (requiresOpencodeBinary(args.mode)) {
    const opencodeCheck = await checkOpencodeAvailability();
    if (!opencodeCheck.available) {
      console.error(opencodeCheck.diagnostics ?? "opencode binary not found in PATH.");
      return 1;
    }

    extraPathDirs = opencodeCheck.resolvedBinDir ? [opencodeCheck.resolvedBinDir] : [];
  }

  await mkdir(MANUAL_RUNS_ROOT, { recursive: true });
  const runRoot = await mkdtemp(join(MANUAL_RUNS_ROOT, "run-"));

  const workspace = validatedProjectPath
    ? await createProjectPathWorkspace(validatedProjectPath, { tempRoot: runRoot })
    : await createFixtureWorkspace(args.fixture as FixtureName, { tempRoot: runRoot });
  let pluginPathUsed = "<none>";
  let resolvedInstalledPackage = "<none>";
  let resolvedHostConfig = "<none>";
  let expectedPluginVersion = "<none>";
  let workspaceDependenciesPrepared = false;
  let aiResourcesPrepared = false;
  let aiResourceStrategy: "none" | "seeded" | "aimgr-installed" = "none";
  let pluginBootstrapSummary = "pending";
  let exitCode = 1;
  let seededAuthPath: string | null = null;
  let authSourceCategory: string = "none";

  try {
    const openCodeBootstrapRequired = requiresOpenCodeBootstrap(args.mode);
    let selectedPluginSource = args.pluginSource;

    const isolatedPaths = openCodeBootstrapRequired
      ? await createIsolatedOpenCodePaths(workspace.tempRoot, {
          prewarmOpenCodeData: true,
        })
      : await createIsolatedOpenCodePaths(workspace.tempRoot, {
          prewarmOpenCodeData: true,
        });

    if (openCodeBootstrapRequired) {
      const hostEnvForPluginPrep: NodeJS.ProcessEnv = {
        ...process.env,
      };

      for (const key of Object.keys(hostEnvForPluginPrep)) {
        if (
          key === "HOME" ||
          key === "XDG_CONFIG_HOME" ||
          key === "XDG_DATA_HOME" ||
          key === "XDG_CACHE_HOME" ||
          key === "BUN_INSTALL" ||
          key === "NODE_AUTH_TOKEN" ||
          key.startsWith("OPENCODE_") ||
          key.startsWith("NPM_CONFIG_") ||
          key.startsWith("npm_config_")
        ) {
          delete hostEnvForPluginPrep[key];
        }
      }

      if (process.env.NODE_AUTH_TOKEN?.trim()) {
        hostEnvForPluginPrep.NODE_AUTH_TOKEN = process.env.NODE_AUTH_TOKEN;
      }

      const preparedPluginSource = await prepareWorkspacePluginSource({
        projectRoot: PROJECT_ROOT,
        opencodeConfigDir: isolatedPaths.opencodeConfigDir,
        pluginSource: args.pluginSource,
        hostEnv: hostEnvForPluginPrep,
      });

      selectedPluginSource = preparedPluginSource.pluginSource;
      pluginPathUsed = preparedPluginSource.localPluginSymlink ?? "<none>";
      resolvedInstalledPackage = preparedPluginSource.resolvedInstalledPackageSpec ?? "<none>";
      resolvedHostConfig = preparedPluginSource.resolvedHostConfigPath ?? "<none>";
      expectedPluginVersion = preparedPluginSource.expectedLoadedPluginVersion ?? "<none>";
      workspaceDependenciesPrepared = preparedPluginSource.workspaceDependenciesPrepared;
      pluginBootstrapSummary = `prepared (${selectedPluginSource})`;

    }

    if (openCodeBootstrapRequired) {
      const preparedCoderResources = await prepareCoderFixtureResources({
        projectRoot: PROJECT_ROOT,
        workdir: workspace.workdir,
        opencodeConfigDir: isolatedPaths.opencodeConfigDir,
        fixtureName: workspace.fixtureName,
        pluginSource: selectedPluginSource,
        env: {
          ...process.env,
          ...isolatedPaths.env,
        },
      });
      aiResourcesPrepared = preparedCoderResources.prepared;
      aiResourceStrategy = preparedCoderResources.strategy;
    }

    if (authSeedPath) {
      seededAuthPath = await seedIsolatedOpenCodeAuth(isolatedPaths, {
        authJsonPath: authSeedPath.authJsonPath,
      });
      authSourceCategory = authSeedPath.source;
    }

    console.log("\nManual plugin test environment ready\n");
    printSection("Mode", args.mode);
    printSection("Plugin source", args.pluginSource);
    printSection(
      "Execution model",
      workspace.workspaceSource.kind === "fixture"
        ? "fixture copy (disposable workspace)"
        : "direct project path (target project left in place)"
    );
    if (workspace.workspaceSource.kind === "fixture") {
      printSection("Fixture", workspace.workspaceSource.fixtureName);
    } else {
      printSection("Project path", workspace.workspaceSource.projectPath);
    }
    printSection("Project source", workspace.projectSourceDir);
    printSection("Temp root", workspace.tempRoot);
    printSection("Workdir", workspace.workdir);
    printSection("Plugin bootstrap", pluginBootstrapSummary);
    printSection("Plugin path used", pluginPathUsed);
    printSection("Resolved installed package", resolvedInstalledPackage);
    printSection("Resolved host config", resolvedHostConfig);
    printSection("Expected loaded plugin version", expectedPluginVersion);
    printSection("Workspace plugin dependencies prepared", workspaceDependenciesPrepared ? "yes" : "no");
    printSection(
      "AI resources prepared",
      aiResourcesPrepared ? `yes (${aiResourceStrategy})` : "no"
    );
    printSection("Isolated HOME", isolatedPaths.homeDir);
    printSection("Isolated XDG_CONFIG_HOME", isolatedPaths.xdgConfigHome);
    printSection("Isolated XDG_DATA_HOME", isolatedPaths.xdgDataHome);
    printSection("Isolated XDG_CACHE_HOME", isolatedPaths.xdgCacheHome);
    printSection("Isolated OPENCODE_CONFIG_DIR", isolatedPaths.opencodeConfigDir);
    printSection(
      "Isolated OpenCode data prewarmed",
      isolatedPaths.prewarmedOpenCodeData === "applied"
        ? "yes (empty baseline copied)"
        : isolatedPaths.prewarmedOpenCodeData === "skipped"
          ? `no (skipped: ${isolatedPaths.prewarmedOpenCodeDataReason ?? "unknown reason"})`
          : "no"
    );
    printSection(
      "Configured plugin loading",
      Object.prototype.hasOwnProperty.call(isolatedPaths.env, "OPENCODE_DISABLE_DEFAULT_PLUGINS")
        ? "disabled (OPENCODE_DISABLE_DEFAULT_PLUGINS=true)"
        : "enabled"
    );
    printSection("Auth seeded", seededAuthPath ? `yes (${authSourceCategory})` : "no");
    printSection(
      "Cleanup plan",
      workspace.workspaceSource.kind === "fixture"
        ? "preserve copied workspace and isolated environment"
        : "preserve isolated environment only; target project remains in place and launcher-owned config stays isolated"
    );
    if (args.keep) {
      printSection("--keep", "accepted (backward-compatible no-op)");
    }
    if (args.mode === "command") {
      printSection("One-shot command", args.command.join(" "));
    }
    console.log("");

    const childEnv = buildChildEnv(args.mode, isolatedPaths.env, extraPathDirs);

    if (args.mode === "tui") {
      const result = await runInteractive(["opencode"], workspace.workdir, childEnv);
      exitCode = result.exitCode;
      console.log(`\nOpenCode TUI finished (${exitReason(result.exitCode, result.signalCode)}).`);
    } else if (args.mode === "shell") {
      const shell = process.env.SHELL?.trim() || "/bin/sh";
      await ensureInteractiveShellStartupReady(shell, childEnv);
      const result = await runInteractive(buildInteractiveShellCommand(shell), workspace.workdir, childEnv);
      exitCode = result.exitCode;
      console.log(`\nShell session finished (${exitReason(result.exitCode, result.signalCode)}).`);
    } else {
      const result = await runCaptured(args.command, workspace.workdir, childEnv);
      if (result.stdout.trim().length > 0) {
        console.log("--- stdout ---");
        process.stdout.write(result.stdout);
        if (!result.stdout.endsWith("\n")) {
          process.stdout.write("\n");
        }
      }

      if (result.stderr.trim().length > 0) {
        console.log("--- stderr ---");
        process.stdout.write(result.stderr);
        if (!result.stderr.endsWith("\n")) {
          process.stdout.write("\n");
        }
      }

      exitCode = result.exitCode;

      console.log(`--- result ---\nExit: ${exitReason(result.exitCode, result.signalCode)}`);
    }
  } catch (error) {
    console.error(`Launcher failed: ${(error as Error).message}`);
    exitCode = 1;
  } finally {
    console.log(`Environment preserved at: ${workspace.tempRoot}`);
  }

  return exitCode;
}

if (import.meta.main) {
  const code = await main();
  process.exit(code);
}
